name: Build and deploy website

on:
  push:
    branches:
      - main

env:
  REACT_APP_FONT_PICKER_API_KEY: ${{ secrets.FONT_PICKER_API_KEY }}
  REACT_APP_PRODUCT_ID: ${{ secrets.PRODUCT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate website files
        run: npm run build

      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: "README.md"
          target: "build/README.md"

      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: "LICENSE"
          target: "build/LICENSE"

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        with:
          build_dir: build/
          email: ${{ secrets.EMAIL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
